Repository sfstar/hass-victron, pull requests merged in 2025-07, with the labels that each got.

#339 Update README.md: clarified the manual installation and corrected some typos
  README.md
Labels: documentation

#281 Feature/prepare for pymodbus 3 9 0
  custom_components/victron/binary_sensor.py
  custom_components/victron/coordinator.py
  custom_components/victron/hub.py
  custom_components/victron/sensor.py
  custom_components/victron/switch.py
  pyproject.toml
Labels: minor, dependencies

#341 initial attempt at supporting core 2025.2 till 2025.6 and 2025.7
  custom_components/victron/hub.py
  custom_components/victron/manifest.json
  hacs.json
Labels: bugfix
